"""DelibraShift's public schema and deterministic Windrift primitives."""

from .adapters import NIMAdapter, OllamaAdapter
from .archive import PackArchive, build_pack_archive, verify_pack_archive
from .bank import PackError, load_pack, load_pack_metadata
from .clock import WindowAdvance, advance_deliberation, latch_action
from .harness import (
    HarnessAgent,
    TransportPacer,
    parse_action_reply,
    parse_choice_reply,
    parse_prediction_reply,
    parse_reply,
    render_prompt,
)
from .gates import (
    KillCriterionGate,
    MatchedStateGate,
    ReproducibilityGate,
    decoy_goal,
    kill_criterion_gate,
    matched_state_gate,
    reproducibility_gate,
    score_feedback_use,
)
from .experiments import (
    AblationEpisode,
    ArmSummary,
    FeedbackEpisode,
    FeedbackSummary,
    MatchedPairReport,
    MetricRange,
    ProbeEpisode,
    run_matched_pair,
    write_matched_pair_report,
)
from .oracle import (
    LeadGreedyAgent,
    OracleAgent,
    StaleReactorAgent,
    oracle_action,
)
from .probes import (
    CHOICE_PROBE_PROMPT_VERSION,
    FORMAT_PROBE_PROMPT_VERSION,
    ForcedChoiceCandidates,
    ForcedChoiceScore,
    FormatProbeScore,
    forced_choice_candidates,
    render_forced_choice_prompt,
    render_format_probe_prompt,
    score_forced_choice_probe,
    score_format_probe,
)
from .scoring import (
    PredictionFidelityScore,
    TemporalAnticipationScore,
    score_episode,
    score_outcome,
    score_prediction_fidelity,
    score_temporal_anticipation,
)
from .scaffold import (
    SCAFFOLD_PROMPT_VERSION,
    WMScaffoldAgent,
    render_action_prompt,
    render_prediction_prompt,
)
from .types import (
    NOOP_ACTION,
    SCHEMA_VERSION,
    Action,
    Adapter,
    AgentReply,
    EpisodeScores,
    GroundTruthState,
    Observation,
    PackScores,
    Prediction,
    ScenarioConfig,
    WindComponent,
)
from .world import advance_ticks, build_observation, initial_state, step

__all__ = [
    "NOOP_ACTION",
    "NIMAdapter",
    "OllamaAdapter",
    "SCHEMA_VERSION",
    "Action",
    "AblationEpisode",
    "Adapter",
    "AgentReply",
    "ArmSummary",
    "FeedbackEpisode",
    "FeedbackSummary",
    "EpisodeScores",
    "GroundTruthState",
    "CHOICE_PROBE_PROMPT_VERSION",
    "FORMAT_PROBE_PROMPT_VERSION",
    "ForcedChoiceCandidates",
    "ForcedChoiceScore",
    "FormatProbeScore",
    "KillCriterionGate",
    "MatchedStateGate",
    "MatchedPairReport",
    "MetricRange",
    "Observation",
    "OracleAgent",
    "LeadGreedyAgent",
    "StaleReactorAgent",
    "PackError",
    "PackArchive",
    "PackScores",
    "Prediction",
    "ProbeEpisode",
    "PredictionFidelityScore",
    "ReproducibilityGate",
    "TemporalAnticipationScore",
    "TransportPacer",
    "SCAFFOLD_PROMPT_VERSION",
    "ScenarioConfig",
    "WindComponent",
    "WindowAdvance",
    "WMScaffoldAgent",
    "advance_deliberation",
    "advance_ticks",
    "build_observation",
    "build_pack_archive",
    "decoy_goal",
    "forced_choice_candidates",
    "load_pack",
    "load_pack_metadata",
    "initial_state",
    "kill_criterion_gate",
    "latch_action",
    "matched_state_gate",
    "parse_reply",
    "parse_action_reply",
    "parse_choice_reply",
    "parse_prediction_reply",
    "oracle_action",
    "render_prompt",
    "render_action_prompt",
    "render_prediction_prompt",
    "render_forced_choice_prompt",
    "render_format_probe_prompt",
    "reproducibility_gate",
    "score_prediction_fidelity",
    "score_temporal_anticipation",
    "score_outcome",
    "score_episode",
    "score_feedback_use",
    "score_forced_choice_probe",
    "score_format_probe",
    "run_matched_pair",
    "step",
    "verify_pack_archive",
    "write_matched_pair_report",
    "HarnessAgent",
]
